iry_appli_home:
    path:   /
    defaults: {_controller: IRYAppliBundle:Default:home}
iry_appli_choixcours:
    path:   /choixcours/{helicopter_id}
    defaults: {_controller: "IRYAppliBundle:Default:choixcours"}
