iry_appli_home:
    path:   /
    defaults: {_controller: IRYAppliBundle:Application:home}

iry_appli_choixcours:
    path:   /choixcours/{helicopter_id}
    defaults: {_controller: "IRYAppliBundle:Application:choixcours"}
iry_appli_cm:
    path:   /theoretical-course/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:coursMagistral"}
iry_appli_cd:
    path:   /demonstrative-course/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:coursDemonstratif"}
iry_appli_vi:
    path:   /immersive-movie/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:videoImmersive"}
iry_appli_ep:
    path:   /practical-training/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:exercicePratique"}
iry_appli_ep_pilot:
    path:   /practical-training/{course_id}/pilot/{pilot_id}
    defaults: {_controller: "IRYAppliBundle:Application:exercicePratiqueVuePilote"}
iry_appli_dc:
    path:   /defriefing/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:debriefing"}

iry_crud:
    path:   /crud
    defaults: {_controller: IRYAppliBundle:Application:crud}
iry_crud_heli_create:
    path:   /crud/helicopter/create
    defaults: {_controller: IRYAppliBundle:CrudHelicopter:createHelicopter}
iry_crud_heli_list:
    path:   /crud/helicopters
    defaults: {_controller: IRYAppliBundle:CrudHelicopter:helicopters}
iry_crud_heli_update:
    path:   /crud/helicopter/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudHelicopter:updateHelicopter}
iry_crud_heli_delete:
    path:   /crud/helicopter/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudHelicopter:deleteHelicopter}
iry_crud_theme_list:
    path:   /crud/themes
    defaults: {_controller: IRYAppliBundle:CrudTheme:themes}
iry_crud_theme_delete:
    path:   /crud/theme/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudTheme:deleteTheme}
iry_crud_theme_update:
    path:   /crud/theme/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudTheme:updateTheme}
iry_crud_course_list:
    path:   /crud/courses
    defaults: {_controller: IRYAppliBundle:CrudCourse:courses}
iry_crud_course_delete:
    path:   /crud/course/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudCourse:deleteCourse}
iry_crud_course_update:
    path:   /crud/course/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudCourse:updateCourse}
iry_crud_step_list:
    path:   /crud/steps
    defaults: {_controller: IRYAppliBundle:CrudStep:steps}
iry_crud_step_delete:
    path:   /crud/step/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudStep:deleteStep}
iry_crud_step_update:
    path:   /crud/step/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudStep:updateStep}
iry_crud_serie_list:
    path:   /crud/series
    defaults: {_controller: IRYAppliBundle:CrudSerie:series}
iry_crud_serie_create:
    path:   /crud/serie/create
    defaults: {_controller: IRYAppliBundle:CrudSerie:createSerie}
iry_crud_serie_delete:
    path:   /crud/serie/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudSerie:deleteSerie}
iry_crud_serie_update:
    path:   /crud/serie/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudSerie:updateSerie}
iry_crud_theme_list:
    path:   /crud/themes
    defaults: {_controller: IRYAppliBundle:CrudTheme:themes}
iry_crud_theme_create:
    path:   /crud/theme/create
    defaults: {_controller: IRYAppliBundle:CrudTheme:createTheme}
iry_crud_theme_delete:
    path:   /crud/theme/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudTheme:deleteTheme}
iry_crud_theme_update:
    path:   /crud/theme/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudTheme:updateTheme}
iry_crud_subTheme_list:
    path:   /crud/subThemes
    defaults: {_controller: IRYAppliBundle:CrudSubTheme:subThemes}
iry_crud_subTheme_create:
    path:   /crud/subTheme/create
    defaults: {_controller: IRYAppliBundle:CrudSubTheme:createSubTheme}
iry_crud_subTheme_delete:
    path:   /crud/subTheme/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudSubTheme:deleteSubTheme}
iry_crud_subTheme_update:
    path:   /crud/subTheme/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudSubTheme:updateSubTheme}
iry_crud_images:
    path:   /crud/images/
    defaults: {_controller: IRYAppliBundle:CrudImage:images}
iry_crud_image_create:
    path:   /crud/image/create
    defaults: {_controller: IRYAppliBundle:CrudImage:createImage}
iry_crud_image_delete:
    path:   /crud/image/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudImage:deleteImage}
iry_crud_image_update:
    path:   /crud/image/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudImage:updateImage}
iry_crud_immersiveMovies:
    path:   /crud/immersiveMovies/
    defaults: {_controller: IRYAppliBundle:CrudImmersiveMovie:immersiveMovies}
iry_crud_immersiveMovie_create:
    path:   /crud/immersiveMovie/create
    defaults: {_controller: IRYAppliBundle:CrudImmersiveMovie:createImmersiveMovie}
iry_crud_immersiveMovie_delete:
    path:   /crud/immersiveMovie/{id}/delete
    defaults: {_controller: IRYAppliBundle:CrudImmersiveMovie:deleteImmersiveMovie}
iry_crud_immersiveMovie_update:
    path:   /crud/immersiveMovie/{id}/update
    defaults: {_controller: IRYAppliBundle:CrudImmersiveMovie:updateImmersiveMovie}




iry_rest_set_as_favorite:
    path:   /rest/result_favorite/{id}
    defaults: {_controller: IRYAppliBundle:REST:setResultToFavorite}
    methods:   [GET]

iry_rest_get_last_instruction:
    path:   /rest/last_instruction/{id}
    defaults: {_controller: IRYAppliBundle:REST:getLastInstruction}
    methods:   [GET]

iry_rest_get_course_instruction:
    path:   /rest/course_instructions/{id}
    defaults: {_controller: IRYAppliBundle:REST:getCourseInstructions}
    methods:   [GET]

iry_rest_demonstrative_course_show:
    path:   /rest/demonstrative_show/{course}/{step}
    defaults: {_controller: IRYAppliBundle:REST:demonstrativeCourseShow}
    methods:   [GET]

iry_rest_post_step:
    path:   /rest/poststep/{step}/{pilot}/{success}
    defaults: {_controller: IRYAppliBundle:REST:postStep}
    methods:   [GET]

iry_rest_call_instructor:
    path:   /rest/call_instructor/{pilot}
    defaults: {_controller: IRYAppliBundle:REST:callInstructor}
    methods:   [GET]

# iry_folder_theoretical_course:
#     defaults: { /src/IRY/AppliBundle/Resources/public/cm }

iry_rest_send_image:
    path:   /rest/sendImage/{url}
    defaults: {_controller: IRYAppliBundle:REST:sendImage}
    methods:   [GET]
    requirements:
        url: .+
