iry_appli_home:
    path:   /
    defaults: {_controller: IRYAppliBundle:Application:home}

iry_appli_choixcours:
    path:   /choixcours/{helicopter_id}
    defaults: {_controller: "IRYAppliBundle:Application:choixcours"}
# iry_appli_step:
#     path:   /step/{course_id}
#     defaults: {_controller: "IRYAppliBundle:Application:step"}
iry_appli_cm:
    path:   /theorical-course/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:coursMagistral"}
iry_appli_cd:
    path:   /demonstrative-course/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:coursDemonstratif"}
iry_appli_vi:
    path:   /immersive-movie/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:videoImmersive"}
iry_appli_ep:
    path:   /practical-training/{course_id}
    defaults: {_controller: "IRYAppliBundle:Application:exercicePratique"}
iry_appli_pilot:
    path:   /practical-training/{course_id}/pilot/{pilot_id}
    defaults: {_controller: "IRYAppliBundle:Application:exercicePratiqueVuePilote"}
iry_appli_dc:
    path:   /defriefing/
    defaults: {_controller: "IRYAppliBundle:Application:debriefing"}

iry_appli_ep_centre_pilote:
    path:   /practical-training/{course_id}/view-pilot/{pilot_id}
    defaults: {_controller: "IRYAppliBundle:Application:exercicePratiqueCentrePilote"}

iry_crud_heli_list:
    path:   /crud/helicopters
    defaults: {_controller: IRYAppliBundle:Crud:helicopters}
iry_crud_heli_delete:
    path:   /crud/helicopter/{id}/delete
    defaults: {_controller: IRYAppliBundle:Crud:deleteHelicopter}
iry_crud_heli_update:
    path:   /crud/helicopter/{id}/update
    defaults: {_controller: IRYAppliBundle:Crud:updateHelicopter}

iry_crud_theme_list:
    path:   /crud/themes
    defaults: {_controller: IRYAppliBundle:Crud:themes}
iry_crud_theme_delete:
    path:   /crud/theme/{id}/delete
    defaults: {_controller: IRYAppliBundle:Crud:deleteTheme}
iry_crud_theme_update:
    path:   /crud/theme/{id}/update
    defaults: {_controller: IRYAppliBundle:Crud:updateTheme}

iry_crud_course_list:
    path:   /crud/courses
    defaults: {_controller: IRYAppliBundle:Crud:courses}
iry_crud_course_delete:
    path:   /crud/course/{id}/delete
    defaults: {_controller: IRYAppliBundle:Crud:deleteCourse}
iry_crud_course_update:
    path:   /crud/course/{id}/update
    defaults: {_controller: IRYAppliBundle:Crud:updateCourse}


# iry_rest_helicopters:
#     path:   /rest/helicopters
#     defaults: {_controller: IRYAppliBundle:REST:helicopters}
#     methods:   [GET]
# iry_rest_helicopter:
#     path:   /rest/helicopter/{id}
#     defaults: {_controller: IRYAppliBundle:REST:helicopter}
#     methods:   [GET]
# iry_rest_helicopter_add:
#     path:   /rest/helicopter/{id}
#     defaults: {_controller: IRYAppliBundle:REST:helicopterPost}
#     methods:   [POST]
