parameters:
#    iry_appli.example.class: IRY\AppliBundle\Example

services:
#    iry_appli.example:
#        class: %iry_appli.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    application_controller:
        class: IRY\AppliBundle\Controller\ApplicationController