iry_web_doc:
    resource: "@IRYWebDocBundle/Resources/config/routing.yml"
    prefix:   /

iry_api:
    resource: "@IRYApiBundle/Resources/config/routing.yml"
    prefix:   /api

iry_security:
    resource: "@IRYSecurityBundle/Resources/config/routing.yml"
    prefix:   /

iry_appli:
    resource: "@IRYAppliBundle/Resources/config/routing.yml"
    prefix:   /application/

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /_console

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc