parameters:
#    iry_security.example.class: IRY\SecurityBundle\Example

services:
#    iry_security.example:
#        class: %iry_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    login_listener:
        class: 'IRY\SecurityBundle\Listener\LoginListener'
        arguments: ['@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
