IRY\AppliBundle\Entity\Pilot:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        isCalling:
            expose: true
    virtual_properties:
        getNbErrors:
          serialized_name: nb_errors
        getNbSuccess:
          serialized_name: nb_success
        getCurrentStep:
          serialized_name: current_step
        getJavascriptTimestampDateCalling:
          serialized_name: date_calling