iry_api_main:
    resource: "@IRYApiBundle/Controller/"
    type:     annotation

pilots:
    type: rest
    resource: IRY\ApiBundle\Controller\PilotController

immersive_application_data:
    type: rest
    resource: IRY\ApiBundle\Controller\ImmersiveApplicationDataController

serie:
    type: rest
    resource: IRY\ApiBundle\Controller\SerieController

procedure:
    type: rest
    resource: IRY\ApiBundle\Controller\ProcedureController

result:
    type: rest
    resource: IRY\ApiBundle\Controller\ResultController
