IRY\AppliBundle\Entity\Course:
    type: entity
    table: Course
    repositoryClass: IRY\AppliBundle\Entity\CourseRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        theme: #le champ de l'entité Course
            targetEntity: Theme #L'entité cible
            inversedBy: course #le champ dans l'entité cible
            joinColumn:
                name: theme_id #colonne de jointure
                referencedColumnName: id #jointure faite par l'id du theme