IRY\AppliBundle\Entity\Course:
    type: entity
    table: Course
    repositoryClass: IRY\AppliBundle\Entity\CourseRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        subTheme: #le champ de l'entité Course
            targetEntity: SubTheme #L'entité cible
            inversedBy: courses #le champ dans l'entité cible
            joinColumn:
                name: subTheme_id #colonne de jointure
                referencedColumnName: id #jointure faite par l'id du 
        typeCourse: #le champ de l'entité Course
            targetEntity: TypeCourse #L'entité cible
            inversedBy: courses #le champ dans l'entité cible
            joinColumn:
                name: typeCourse_id #colonne de jointure
                referencedColumnName: id #jointure faite par l'id du
    oneToMany:
        steps: #Champ dans l'entité Helicopter
            targetEntity: Step #Entité visée
            mappedBy: course #Champ dans l'entité visée
        images:
            targetEntity: Image #Entité visée
            mappedBy: course #Champ dans l'entité visée
    oneToOne:
        immersiveMovie:
            nullable: true
            targetEntity: ImmersiveMovie
            joinColumn:
                name: immersiveMovie_id
                referencedColumnName: id
    manyToMany:
        series:
          targetEntity: Serie
          mappedBy: courses
