IRY\AppliBundle\Entity\Helicopter:
    type: entity
    table: Helicopter
    repositoryClass: IRY\AppliBundle\Entity\HelicopterRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
    oneToMany:
        themes:
            targetEntity: Theme
            mappedBy: helicopter