IRY\AppliBundle\Entity\Helicopter:
    type: entity
    table: Helicopter
    repositoryClass: IRY\AppliBundle\Entity\HelicopterRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
        type:
            type: string
            length: 255
    oneToMany:
        themes: #Champ dans l'entité Helicopter
            targetEntity: Theme #Entité visée
            mappedBy: helicopter #Champ dans l'entité visée