IRY\AppliBundle\Entity\Pilot:
    type: entity
    table: Pilot
    repositoryClass: IRY\AppliBundle\Entity\PilotRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            nullable: true
        isCalling:
            type: boolean
            nullable: true
        dateCalling:
            type: datetime
            nullable: true
    oneToMany:
        results: #Champ dans l'entité Helicopter
            targetEntity: Result #Entité visée
            mappedBy: pilot #Champ dans l'entité visée
    manyToOne:
        serie:
            targetEntity: Serie
            joinColumn:
                name: serie_id
                referencedColumnName: id