IRY\AppliBundle\Entity\Pilot:
    type: entity
    table: Pilot
    repositoryClass: IRY\AppliBundle\Entity\PilotRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
        isCalling:
            type: boolean
        dateCalling:
            type: datetime
    oneToMany:
        results: #Champ dans l'entité Helicopter
            targetEntity: Result #Entité visée
            mappedBy: pilot #Champ dans l'entité visée