IRY\AppliBundle\Entity\Result:
    type: entity
    table: Result
    repositoryClass: IRY\AppliBundle\Entity\ResultRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        isError:
            type: boolean
        isFavorite:
            type: boolean
        isGlobal:
            type: boolean
    manyToOne:
        pilot:
            targetEntity: Pilot
            inversedBy: result
            joinColumn:
                name: pilot_id
                referencedColumnName: id
        step:
            targetEntity: Step
            inversedBy: result
            joinColumn:
                name: step_id
                referencedColumnName: id
    oneToOne:
        trial:
            targetEntity: Trial
            # inversedBy: result
            joinColumn:
                name: trial_id
                referencedColumnName: id