IRY\AppliBundle\Entity\SchemaImage:
    type: entity
    table: SchemaImage
    repositoryClass: IRY\AppliBundle\Entity\SchemaImageRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        img:
            type: text

    manyToOne:
        course:
            nullable: true
            targetEntity: Course
            inversedBy: schemaimages
            joinColumn:
                name: course_id
                referencedColumnName: id