IRY\AppliBundle\Entity\Step:
    type: entity
    table: Step
    repositoryClass: IRY\AppliBundle\Entity\StepRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
        order:
            type: integer
    manyToOne:
        course:
            targetEntity: Course
            inversedBy: steps
            joinColumn:
                name: course_id
                referencedColumnName: id
