IRY\AppliBundle\Entity\Theme:
    type: entity
    table: Step
    repositoryClass: IRY\AppliBundle\Entity\StepRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        course: #le champ de l'entité Course
            targetEntity: Course #L'entité cible
            inversedBy: Step #le champ dans l'entité cible
            joinColumn:
                name: course_id #colonne de jointure
                referencedColumnName: id #jointure faite par l'id de l'hélicoptère
    oneToMany:
        result: #Champ dans l'entité Helicopter
            targetEntity: Result #Entité visée
            mappedBy: Step #Champ dans l'entité visée