IRY\AppliBundle\Entity\SubTheme:
    type: entity
    table: SubTheme
    repositoryClass: IRY\AppliBundle\Entity\SubThemeRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        theme:
            targetEntity: Theme
            inversedBy: subthemes
            joinColumn:
                name: theme_id
                referencedColumnName: id
    oneToMany:
        courses:
            targetEntity: Course
            mappedBy: subTheme