IRY\AppliBundle\Entity\Theme:
    type: entity
    table: SubTheme
    repositoryClass: IRY\AppliBundle\Entity\SubThemeRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        Theme: #le champ de l'entité SubTheme
            targetEntity: Theme #L'entité cible
            inversedBy: subthemes #le champ dans l'entité cible
            joinColumn:
                name: theme_id #colonne de jointure
                referencedColumnName: id #jointure faite par l'id du theme
    oneToMany:
        courses: #Champ dans l'entité Helicopter
            targetEntity: Course #Entité visée
            mappedBy: subtheme #Champ dans l'entité visée