IRY\AppliBundle\Entity\Theme:
    type: entity
    table: Theme
    repositoryClass: IRY\AppliBundle\Entity\ThemeRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        helicopter: #le champ de l'entité Theme
            targetEntity: Helicopter #L'entité cible
            inversedBy: themes #le champ dans l'entité cible
            joinColumn:
                name: helicopter_id #colonne de jointure
                referencedColumnName: id #jointure faite par l'id de l'hélicoptère
    oneToMany:
        courses: #Champ dans l'entité Helicopter
            targetEntity: Course #Entité visée
            mappedBy: theme #Champ dans l'entité visée