IRY\AppliBundle\Entity\Type:
    type: entity
    table: Type
    repositoryClass: IRY\AppliBundle\Entity\TypeRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
    fields:
        name:
            type: string
            length: 255
        
    oneToMany:
        Helicopter: #Champ dans l'entité Type
            targetEntity: Helicopter #Entité visée
            mappedBy: Type #Champ dans l'entité visée

            Course: #Champ dans l'entité Type
            targetEntity: Course #Entité visée
            mappedBy: Type #Champ dans l'entité visée